<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_List</name>
   <tag></tag>
   <elementGuidId>16af3f60-617c-4661-afc0-a579ee76d91e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='yui_3_18_1_1_1704868420475_326']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_18_1_1_1704868420475_326 > li > a.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9197cf7-57db-4d3c-a490-e3b8147823f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>3aec92aa-84aa-4c48-b714-791d6fa0dc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2a776598-ddae-4631-80fa-2f8ad4f8d122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-option</name>
      <type>Main</type>
      <value>display</value>
      <webElementGuid>ad5021ff-fa7a-4f4d-9814-d40935669e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ec7fa0d6-57b0-4966-9ed1-62d311177dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pref</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>1ace050f-0b78-4654-908e-95abfeadfb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Switch to list view</value>
      <webElementGuid>7e521b11-826d-4df0-b280-f352794b76f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>courses-view-659e3a4508943659e3a45089451</value>
      <webElementGuid>42e8aa0e-6bac-4f82-ace1-bc4baac41324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f6e57460-c5fe-4943-937f-0684cb187708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    List
                                </value>
      <webElementGuid>5d752a35-c736-412c-927b-d13b0f3a68e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_18_1_1_1704868420475_326&quot;)/li[1]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>945633a3-4c81-4fbe-8c5a-1c114100444a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='yui_3_18_1_1_1704868420475_326']/li/a</value>
      <webElementGuid>a4267040-55fc-4c53-ae4d-825dc4738be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'List')]</value>
      <webElementGuid>1dd51978-9dd3-4aa5-a0cf-67334e85b231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/following::a[1]</value>
      <webElementGuid>73dc3817-d908-4a02-8848-8cce55c16493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by last accessed'])[1]/following::a[3]</value>
      <webElementGuid>aaddc380-bbb2-4910-ae4f-9488d08a4f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course is starred'])[1]/preceding::a[3]</value>
      <webElementGuid>fc3e8bfa-efc4-4a5e-8cce-71f4934a0498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course name'])[1]/preceding::a[3]</value>
      <webElementGuid>dc084190-a63b-42b3-9b80-7c5caa6060db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='List']/parent::*</value>
      <webElementGuid>6387c718-2bb2-4406-ae43-d32a4dc41f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>6195f3ff-15df-4eca-939b-d14918f8d573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>7db62abd-d01d-4625-84cd-15143edae5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                                    List
                                ' or . = '
                                    List
                                ')]</value>
      <webElementGuid>b690b2f7-6a08-4eb1-ae11-c4022fb76781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
