<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search courses_search</name>
   <tag></tag>
   <elementGuidId>4526d027-2663-49f9-9aa9-17fcacb715a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchinput-659e3a4508943659e3a45089451']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchinput-659e3a4508943659e3a45089451</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdd00b8f-9f3b-45a2-bfd5-ed73817ff468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0335b11-e9df-4233-8b3d-b2e2f0344773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-region</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f88ee0b-ac90-493f-b330-d2c30e95f2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>cf41d858-528a-4ccf-b52b-a58aae938211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchinput-659e3a4508943659e3a45089451</value>
      <webElementGuid>6bf1c830-0670-4d12-be34-e50669d5fe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control withclear rounded</value>
      <webElementGuid>97c18c27-d3a2-4e71-b8f7-cb81f30a8200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3a4cf518-f4c1-4c1d-b351-32d47d70a08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>f6616367-d8ea-4945-b8a7-1b1d83427426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2d96edd5-6383-455d-b2ce-7f0cbdf056ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchinput-659e3a4508943659e3a45089451&quot;)</value>
      <webElementGuid>14e8fd02-41c6-4f55-947b-df4048501a97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchinput-659e3a4508943659e3a45089451']</value>
      <webElementGuid>f1d0190f-45bd-4757-8cd0-db5e2f8ae893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchform-auto-659e3a4508943659e3a45089451']/div/input</value>
      <webElementGuid>4624fb42-0090-478a-960f-10cfcb4197b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>188bcc97-fe7a-46d8-bc00-5ca342cb3a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchinput-659e3a4508943659e3a45089451' and @placeholder = 'Search' and @name = 'search']</value>
      <webElementGuid>d5d49f10-4197-4ee8-8d87-064b23175da5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
