<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c3c66550-daf8-4977-938e-101081add074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.bsb-btn-3xl.rounded-pill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ac4121b-4d3e-4e7b-ab74-ace66fb8e14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58a6831d-9995-4f31-a9b4-b9d18dedae28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary bsb-btn-3xl rounded-pill</value>
      <webElementGuid>c0a3b459-6f84-4ace-b2e9-3f47c30c9c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4cf0a395-1de8-4060-8755-d5665988b6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollspyHero&quot;)/div[@class=&quot;container overflow-hidden&quot;]/div[@class=&quot;row gy-3 gy-lg-0 align-items-lg-center justify-content-lg-between&quot;]/div[@class=&quot;col-12 col-lg-6 order-1 order-lg-0&quot;]/div[@class=&quot;d-grid gap-2 d-sm-flex&quot;]/a[1]/button[@class=&quot;btn btn-primary bsb-btn-3xl rounded-pill&quot;]</value>
      <webElementGuid>87a4c1fc-55e3-4ef1-b000-3e0fc60f57fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99253888-48b2-49da-8403-d31fdb2b18d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74740fa6-bd7f-499b-9571-bb2a11c429fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary bsb-btn-3xl rounded-pill</value>
      <webElementGuid>a1f6adf9-d9b1-4b22-ac5f-f52b38e084f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>39b5f68f-dbe4-4fb8-b577-dd85458b7d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollspyHero&quot;)/div[@class=&quot;container overflow-hidden&quot;]/div[@class=&quot;row gy-3 gy-lg-0 align-items-lg-center justify-content-lg-between&quot;]/div[@class=&quot;col-12 col-lg-6 order-1 order-lg-0&quot;]/div[@class=&quot;d-grid gap-2 d-sm-flex&quot;]/a[1]/button[@class=&quot;btn btn-primary bsb-btn-3xl rounded-pill&quot;]</value>
      <webElementGuid>ab0a4c23-28fd-41cb-b79f-3f52c2d5cec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>baba8f62-7d4f-4f78-ab72-d25f1ad1e51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c83693f-0612-44c4-8f77-7464032d4b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary bsb-btn-3xl rounded-pill</value>
      <webElementGuid>e937e00c-7609-4c17-b911-040ab95baf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9bef8142-09ef-4805-a74d-cdd4e09be395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollspyHero&quot;)/div[@class=&quot;container overflow-hidden&quot;]/div[@class=&quot;row gy-3 gy-lg-0 align-items-lg-center justify-content-lg-between&quot;]/div[@class=&quot;col-12 col-lg-6 order-1 order-lg-0&quot;]/div[@class=&quot;d-grid gap-2 d-sm-flex&quot;]/a[1]/button[@class=&quot;btn btn-primary bsb-btn-3xl rounded-pill&quot;]</value>
      <webElementGuid>b9a22a37-1f77-4d14-8f38-6f24d1f6cb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cd4b8d8-2440-4d00-90f3-c76553c175b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d57b35b2-81fd-4f84-a0ca-5453d3d4e683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary bsb-btn-3xl rounded-pill</value>
      <webElementGuid>98568a0b-7bcb-4924-bf3b-67509d710ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>24bc754f-9089-42fc-a04a-76e477bdb02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollspyHero&quot;)/div[@class=&quot;container overflow-hidden&quot;]/div[@class=&quot;row gy-3 gy-lg-0 align-items-lg-center justify-content-lg-between&quot;]/div[@class=&quot;col-12 col-lg-6 order-1 order-lg-0&quot;]/div[@class=&quot;d-grid gap-2 d-sm-flex&quot;]/a[1]/button[@class=&quot;btn btn-primary bsb-btn-3xl rounded-pill&quot;]</value>
      <webElementGuid>d91a1eb7-7959-43ef-b5f7-90ba1a76f01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>e34165bb-07a3-49a4-9e4f-a02c93bd055f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='scrollspyHero']/div/div/div/div/a/button</value>
      <webElementGuid>a7eb0055-3806-4248-82d3-acffaa6e97d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Daring Mahasiswa'])[1]/following::button[1]</value>
      <webElementGuid>41510ece-d98c-4512-864c-ca7fbd161f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Daring Dosen'])[1]/following::button[1]</value>
      <webElementGuid>e1614942-7e05-4ef7-8de8-a090f4f36ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kami'])[1]/preceding::button[1]</value>
      <webElementGuid>83a9d807-2e11-4465-95a8-5080d03946ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>f53f7ba0-0ef9-438f-9f47-71db8e78593d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>e770f615-dd2e-4a11-a71b-bf0cc22e1a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>7959fadf-39d0-4416-89a7-78a8198e6acb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
